#!/usr/bin/env python3
import fileinput
import re
from getopt import gnu_getopt
import sys

from lxml import etree


opts, file = gnu_getopt(sys.argv[1:],"")
portugal=0
tree = etree.parse(file[0])#("history.stackexchange.com/Posts.xml")
root = tree.getroot()
for element in root:
	if element.get('PostTypeId') == '1':
		body=element.get('Body')

		if(re.search('(?i:portugal)',body)):
			portugal = portugal+1
print(portugal)
